templatesadmin/urls.py
from django.contrib.admin.sites import AdminSite
from django.conf.urls import *

urlpatterns = patterns('',
    url(r'^$', 'templatesadmin.views.overview', name='templatesadmin-overview'),
    url(r'^edit/(?P<path>.*)/$', 'templatesadmin.views.edit', name='templatesadmin-edit'),
)

templatesadmin/forms.py
from django import forms
from django.forms.forms import DeclarativeFieldsMetaclass 
from .widgets import CodeMirrorEditor

class CodemirrorForm( forms.Form ):
    """
        Display the code using CodeMirror editor
    """
    content = forms.CharField(
        widget = forms.Textarea(attrs={'rows': 10, 'cols': 40})
    )

    def __init__(self, *args, **kwargs):
        syntax = kwargs.pop('widget_syntax') or 'htmlmixed'

        super(CodemirrorForm, self).__init__( *args, **kwargs )

        #
        # Overwrite editor field dynamically 
        # 
        self.fields['content'] =  forms.CharField(
            widget = CodeMirrorEditor(attrs={'syntax': syntax})
        )

class CodemirrorFormHtml( forms.Form ):
    content = forms.CharField(
        widget = CodeMirrorEditor(attrs={'syntax': 'htmlmixed'})
    )

templatesadmin/templates/templatesadmin/base.html
{% extends "admin/base_site.html" %}

{% block extrahead %}
<!-- -->
<script type="text/javascript">
/* <![CDATA[ */
(function() {
  var saved = window.onload;
  var hash = window.location.hash;
  window.onload = function() {
    saved && saved();
    var elements = document.getElementsByTagName("a");
    for(var i = 0; i< elements.length; i++) {
      if("#" + elements[i].getAttribute("name") == hash) {
        elements[i].parentNode.setAttribute("style", "border: 3px solid red;");
      }
    }
  }
})();
/* ]]> */
</script>

<!-- ajax save -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.0/js.cookie.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.min.js"></script>

<script>
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    var Last_Responce = null,
        options = {
            success: function code_updated(data, status, xhr) {
                Last_Responce = data;
                var errors = $(data).find('.errorlist, .error');
                if (errors.length == 0) {
                    alert("Code updated!");
                } else {
                    alert("Update failed!\n" + errors.text());
                };
            },
            beforeSerialize: function($form, options) {
                console.log('SAVE!');
            },
            beforeSend: function (xhr, settings) {
                var csrftoken = Cookies.get('csrftoken');

                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            },
            data: {
                content: function () {
                    return editor_content.doc.getValue();   
                }
            }
        }

    $(document).ready(function() {
        $('#site_form').ajaxForm(options);

        document.addEventListener("keydown", function(e) {
            if (e.keyCode == 83 && (navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)) {
                e.preventDefault();
                console.log('ctrl-s detect!');
                $('#site_form').ajaxSubmit(options);
            }
        }, false);

        $('#content-main').prepend('<span>Save <b>Ctrl+s</b>! Help <b>Ctrl+h</b>!</span>');
    });

</script>
{% endblock %}

templatesadmin/templates/templatesadmin/edit.html
{% extends "templatesadmin/base.html" %}

{% load i18n admin_modify static %}
{% load templatesadmin_tags %}

{% block extrahead %}
    {{ block.super }}
    {{ media }}
    {{ form.media }}
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
    <style type="text/css">
        textarea#id_content{
            width: 99%;
            height: 400px;
            margin: 0 0 1em 0;
            font-family: monospace;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
     <a href="{% url 'admin:index' %}">{% trans "Home" %}</a> &rsaquo;
     <a href="{% url 'admin:app_list' 'templatesadmin' %}">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
    <a href="{% url 'admin:templatesadmin_ftemplate_changelist' %}">{% trans "File selection" %}</a> &rsaquo;
    {{ template_path }}
</div>
{% endblock %}

{% block title %}
    {% trans "Edit Template:" %} {{ template_path|shortenfilepath }}
{% endblock %}

{% block content_title %}
    <h1>{% trans "Edit Template:" %} {{ template_path|shortenfilepath }}</h1>
{% endblock %}

{% block content %}
<div id="content-main">
    <form enctype="multipart/form-data" action="" method="post" id="site_form">
        {% csrf_token %}
        <div>
            {{ form.errors }}
            {{ form.content }}
        </div>
        <div class="submit-row">
        {% if template_writeable %}
            {% for field in form %}
                {% ifnotequal field.label "Content" %}
            <p class="float-left">
                {{ field.label }} {{ field }}
            </p>
                    {% if forloop.last %} <input type="submit" value="{% trans "Save" %}" class="default" /> {% endif %}
            <br />
                {% endifnotequal %}
            {% endfor %}
        {% else %}
            {% trans "This template is not writeable." %}
            <br />
        {% endif %}
        </div>
    </form>
</div>
{% endblock %}

templatesadmin/templates/templatesadmin/overview.html
{% extends "templatesadmin/base.html" %}

{% load i18n static %}
{% load templatesadmin_tags %}

{% block breadcrumbs %}
<div class="breadcrumbs">
     <a href="{% url 'admin:index' %}">{% trans "Home" %}</a> &rsaquo;
     <a href="{% url 'admin:app_list' 'templatesadmin' %}">{{ opts.verbose_name_plural|capfirst }}</a> &rsaquo;
    {% trans "File selection" %}
</div>
{% endblock %}

{% block title %}Templatesadmin Overview{% endblock %}

{% block content_title %}
    <h1>{% trans "Templatesadmin Overview" %}</h1>
{% endblock %}

{% block content %}
    {% for template in template_dict %}
        {% ifchanged template.rootpath %}
        {% if not forloop.first %}
            </tbody>
        </table>
        </div>
        {% endif %}
        <div class="module">
        <a name="{{ template.rootpath }}"></a>
        <h2>{{ template.rootpath }}</h2>
        <table cellspacing="0" style="width: 100%;">
            <thead>
                <tr>
                    <th>{% trans "File" %}</th>
                    <th class="r">{% trans "Modified" %}</th>
                </tr>
            </thead>
            <tbody>
        {% endifchanged %}
                <tr class="{% cycle 'row1' 'row2' %}">
                    <td style="width: 99%;">
                        {% if not template.writeable %}<img src="{% static 'admin/img/icon-no.gif' %}" alt="{% trans "(read only)" %}" title="{% trans "This template is not writeable." %}" />{% endif %}
                        <a href="{% url 'admin:templatesadmin_ftemplate_change' template.abspath %}">{{ template.abspath|shortenfilepath }}</a></td>
                    <td style="white-space: nowrap;" class="r">{{ template.modified|date:_("DATETIME_FORMAT") }}</td>
                </tr>
    {% endfor %}
            </tbody>
        </table>
        </div>
{% endblock %}